export enum RequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  SYNCED = 'SYNCED',
  SYNC_FAILED = 'SYNC_FAILED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
